apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-fastapi
  template:
    metadata:
      labels:
        app: mlops-fastapi
    spec:
      containers:
        - name: mlops-fastapi
          image: mlops-fastapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
